# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BTCTurkApi' do
    pod 'AFNetworking', '~> 2.5.4'
    pod 'CocoaSecurity', '~> 1.2'
end

target 'BTCTurkApiTests' do

end

